### PR TITLE
Quick fix for bug when ES7 plugin is added to project

### PR DESCRIPTION
**Pull request by ku8ar**

### CODE REVIEW

**Comment by ku8ar** [comment]
To reproduce error:
1. Add esdoc-es7-plugin to esdoc.json
2. Add class with this content:
`export class ExampleComponent {
  render ({...props}) {
  }
}`
Error concerns the plugin, but finally breaks down class parser.
Error probably refers to spread operator stated to object parameter.

**Comment by typhonrt** [comment]
Yeah.. This definitely is related to the object / spread operator. Keep in mind that the esdoc ES7 plugin is experimental and old / out of date and unknown if @h13i32maru will update / maintain it. Though this solution seems reasonable thought he ES7 plugin should also be updated.. 👍

**Comment by typhonrt** [comment]
It should be noted that this problem will go away if the parser is switched to 'babylon' and would deprecate the need for `esdoc-es7-plugin`.

**Comment by h13i32maru** [comment]
@ku8ar Thanks and sorry for late reply 🙇 
I fixed this. And I will release in next version. Please check it via [developing version](https://esdoc.org/manual/usage/usage.html#installation).

**Pull request closed without merging**
