### PR TITLE
Proposed patch for #138

### PR DESCRIPTION
**Pull request by silkentrance**
todo: proper document type-of-decorator

I am still wondering how one would document the exact nature of the decorator in the generated documentation, i.e.

```
public <static method> my_decorator(...): Object

public <class> my_decorator(...): class

public <instance method> my_decorator(...): Object
```

and there is still the problem on how to document it in the first place, e.g.

```
@decorator {static method}

vs.

@decorator {Smethod}

or

@decorator {instance method}

vs.

@decorator {Imethod}
```
and so on.

### CODE REVIEW

**Comment by silkentrance** [comment]
See #138

**Comment by h13i32maru** [comment]
@silkentrance Thanks this PR! However decorator in ES.next is not released. So I can not merge PR. I will implement decorator feature in future version.

**Comment by silkentrance** [comment]
@h13i32maru no problem, I made it for myself so I can use the feature right now. Feel free to use this, though, when reimplementing it.

**Comment by h13i32maru** [comment]
@silkentrance Thanks for your understanding.

**Pull request closed without merging**
