### PR TITLE
fix(nav-sorting): fixes gh-268, entries in nav bar are now sorted bas…

### PR DESCRIPTION
**Pull request by silkentrance**
…ed on their name rather than their long name

### CODE REVIEW

**Comment by silkentrance** [comment]
Some tests are failing, waiting for input before I begin fixing these...

**Comment by silkentrance** [comment]
And, btw. why don't you do differential tests instead? rendering out the docs and then comparing these with a previous rendering. This would make things much easier.

**Comment by h13i32maru** [comment]
@silkentrance Thank you. And sorry about late reply.
Please check latest ESDoc.

**Comment by h13i32maru** [comment]
Please check ESDoc v1.0 and https://github.com/esdoc/esdoc-plugins

Finally, I am sorry that the reaction was delayed 🙇

**Pull request closed without merging**
