### PR TITLE
Make the layout responsive using Less.

### PR DESCRIPTION
**Pull request by avine**
Hi there!

Here's a new layout far more versatile.
And the good news, it's using Less!

### CODE REVIEW

**Comment by avine** [comment]
For now, you need to run first:
`npm run esdoc`

Next, to compile `style.less` to `style.css`, just run:
**`npm run less`**

Finally, run dev server:
`npm run start`

**Comment by avine** [comment]
The entry point of Less file is located here:
`/src/Publisher/Builder/template/less/style.less`

and it contains:
```less
@import "variables";
@import "text";
@import "layout";
@import "menu"; // header menu
@import "search";
@import "nav"; // sidebar navigation
```

**Comment by avine** [comment]
You can check the result at:
http://esdoc.avine.fr/v2

The layout is ready, but the content is still in progress...

**Comment by avine** [comment]
Hi there,

The new design is compatible with `dark-theme` just by updating a few lines of code:
```less
@color-base: #999;
@color-alt: #555;

@bg-color-base: #1e1e1e;
@bg-color-alt: #171717;
@bg-color-highlight: #2e2e2e;

@border-color: #3e3e3e;

@code-bg-color: rgba(255, 255, 255, 0.07);

@table-bg-hover: #111;
```

Feel free to check the result at:
http://esdoc.avine.fr/v2-dark

But don't forget to check the latest `regular-theme`at:
http://esdoc.avine.fr/v2

**Comment by avine** [comment]
Hi there,

It's almost done!

The Less is separated into the following list of imports:
```less
// basics
@import "core/variables";
@import "core/text";
@import "core/layout";
@import "core/menu";
@import "core/search";
@import "core/nav";
@import "core/helper";

// main content
@import "core/doc";
@import "core/summary";
@import "core/manual";

// markdown
@import "core/markdown";
```
 
In the file `.esdoc.json` you can specify the list the `import` you want, and configure the Less `theme` you want, like this:
```javascript
{
  "less": {
    "imports": ["variables", "text", "menu", "search", "nav"], // import only 5 items
    "theme": "dark" // ad theme: '/src/Publisher/Builder/template/less/theme-dark.less'
  }
}
```

Now, the Less to Css compilation is processed in:
`src/Publisher/Builder/LessFileBuilder.js`

So, you just need to run:
`npm run esdoc`

Please check the result at: 
- http://esdoc.avine.fr/v2
- http://esdoc.avine.fr/v2-dark

Here some screenshots:

default-theme

dark-theme

default-content

dark-content

default-source

dark-source

**Comment by avine** [comment]
You can now add your brand logo in `.esdoc.json`:
```json
{
  "logo": "<PATH_TO_LOGO_FROM_ROOT>"
}
```

In `layout.html`:
```html
<a href="./" data-ice="brandLogoLink"></a>
```

In `Builder.js`
```js
if (this._config.logo) {
  const logo = this._config.logo.match(/[^\/]+$/)[0];
  ice.load('brandLogoLink', `<img src=".image/${logo}">`);
} else {
  ice.drop('brandLogoLink');
}
```

In `StaticFileBuilder.js`:
```javascript
if (this._config.logo) {
  const logo = this._config.logo.match(/[^\/]+$/)[0];
  callback(path.resolve(this._config.logo), `.image/${logo}`);
}
```

Here a screenshot using the esdoc logo:
```json
{
  "logo": "./src/Publisher/Builder/template/image/esdoc-logo.svg"
}
```

brand-logo

**Comment by avine** [comment]
Here's the latest dark-theme screenshot:

dark-manual

Any feedback will be appreciated... 👍

**Comment by avine** [comment]
Here's a new theme which is like: http://git-scm.com

gitme

**Comment by crunchie84** [comment]
:heart: one of my biggest issues with the RxJs docs will be solved by this pr

**Comment by avine** [comment]
Here is the way to configure the `less` property in .esdoc.json:

### Load sublist of available Less imports
(notice that "variables" is optional in this list and will be automatically prepended when needed)
```javascript
{
  "less": {
    "imports": [/*"variables", */"layout", "menu", "search", "aside"]
  }
}
```

### Load all available Less imports and add one esdoc theme available
(for now there's 2 themes available: `dark` and  `gitme`)
```javascript
{
  "less": {
    "theme": ["dark"] // alias of `./src/Publisher/Builder/template/less/theme/dark.less`
  }
}
```

### Don't load any import and add one user theme
(allowing you to completely remove the default styles and do your own styles with Less...)
```javascript
{
  "less": {
    "imports": [],
    "theme": ["./my/path/to/less/file.less"] // real path to user theme
  }
}
```

### Use some Less imports and add your own
```javascript
{
  "less": {
    "imports": [/*"variables", */"layout", "menu", "search", "aside"],
    "theme": ["./my/path/to/less/file.less"] // you can use the esdoc Less `variables`
  }
}
```

**Comment by Flux159** [comment]
@avine Really like the work you put in to make esdoc responsive and theme-able using less. There's an issue with trying to use your fork as a package at the moment though. I think you need to add "less" to esdoc's package.json as a dependency to avoid any runtime errors (you may have it globally installed?). 

I tested this by setting my package json to download esdoc from my github fork (had to build the out/ folder of esdoc first and commit that to github so that npm wouldn't fail on install).

Wanted to comment since this seems to be a large pull request that may take some time to get into esdoc master.

**Comment by h13i32maru** [comment]
@avine Thanks for many feature. However this pull request is so big. Please split it to pull requests of each feature.

And use a [plugin API](https://esdoc.org/manual/advanced/api.html#plugin-feature) for your features. Because I am splitting ESDoc to each plugins(https://github.com/esdoc/esdoc/issues/386). After the working I will implement the function using the plugin API.  So I will try not to put as much function as possible into the main repository.

For example, your theme and logo are implemented using the plugin API.

Thanks.

**Comment by avine** [comment]
@Flux159. Actually, i have added `less`as a `devDependencies`.
You think it should be better as a `dependencies` ?

**Comment by avine** [comment]
Here is a deep explanation of what i have done for this PR.

# In summary

I have removed the original file `src/Publisher/Builder/template/css/style.css`.
Now, the final `out/esdoc/css/style.css` is generated programatically.

To generate this file, we are using the Less files in: `esdoc/src/Publisher/Builder/template/less/core/*.less`,
using the script:
`src/Publisher/Builder/LessFileBuilder.js`

# Here is the changes in the repository

### `package.json`

Add `less` in `dependencies`.


### `script/less.js`

This script is NOT used in the esdoc build process.

Use it at design time, when you need to change something in the `less` files and see the result quickly.

- execute `npm run esdoc` once
- change something in `src/Publisher/Builder/template/less/**`
- execute `npm run less` and see the result immediately
- change something again in `less` files...
- execute again `npm run less`
- ...

The script will update the file `out/esdoc/css/style.css` each time it is called.
(the path `out/esdoc` is hard coded)

How it works ?
The script is simply compiling the Less file `src/Publisher/Builder/template/less/style.less`.
Note that this file `style.less` is (also) NOT used in the esdoc build process.


### `src/Publisher/Builder/template/less/style.less`

As we said above in the `script/less.js` section, this Less file is NOT used in the esdoc build process.

At design time, when you run `npm run less`, this is the Less file which is actually compiled.

```less
@import "core/variables";
@import "core/text";
@import "core/layout";
@import "core/menu";
@import "core/search";
@import "core/aside";
@import "core/helper";

@import "core/doc";
@import "core/summary";
@import "core/manual";
@import "core/markdown";

//@import "theme/dark";
//@import "theme/gitme";
```

For example, you can:
- comment the line `@import "core/text";` to see the esdoc output without this Less file...
- uncomment one of the available themes like `//@import "theme/dark";` to see what it looks like.

### `src/Publisher/Builder/template/less/core/manual.less`

Important notice.
In this file i have added this:

```less
.manual-user-index { 
   // ################
   // Just a proposal:
   // remove this part from the "Manual" page...
   display: none;
   // ################
 }
```

Personally, i prefer to see the `.manual-cards` section at the top of the page.
Thus, i have just added a `display: none;` on the `.manual-user-index` section.
But it is up to you to decide if you prefer to keep this part in the manual page or not.

And in the file `src/Publisher/Builder/template/manualCardIndex.html`, i have added a comment about this idea:

```html
<!-- just an idea! remove this part from the "Manual" page... -->
<div class="manual-user-index" data-ice="manualUserIndex"></div>
```


### `src/Publisher/Builder/DocBuilder.js`

Check if `this._config.logo` is available and just add the `` tag in the `layout.html` using `ice`.


### ` src/Publisher/Builder/StaticFileBuilder.js`

Check if `this._config.logo` is available and just copy the image file in `out/esdoc/image/`.


### `src/Publisher/Builder/LessFileBuilder.js`

This is the script used in the `esdoc` build process.
It produce the final `out/esdoc/css/style.css`
(this time, the path `out/esdoc` depends on the `.esdoc.json` configuration:  `destination`)


### `src/Publisher/publish.js`

Add the script `LessFileBuilder.js` in the process:

```js
...
import LessFileBuilder from './Builder/LessFileBuilder.js';
...
new LessFileBuilder(data, config).exec();
```

### `src/Publisher/Builder/template/css/style.css`

The original `style.css` has been removed.


### `src/Publisher/Builder/template/*.html`

In the following templates, wrap the `<table>` with `<div class="esdoc-table-wrapper">`:
(it is designed to make the table content easly scrollable on the axis x)

- `details.html`
- `properties.html`
- `source.html`
- `summary.html`
- `test.html`

```html
<div class="esdoc-table-wrapper">
  <table>
    ...
  </table>
</div>
```


### `src/Publisher/Builder/template/image/`

Some images has been added and some others replaced.
All the images are now in `svg` format.

- `list.svg` and `list-alt.svg`: nav icon on mobile device.
- `down.svg` and `down-alt.svg`: menu icon on mobile device.
- `find.svg` and `find-alt.svg`: search icon
- `github.svg` and `github-alt.svg`: github icon
- `esdoc-logo.svg` and `esdoc-logo-black.svg`: esdoc logo :)

Removed images:
- `esdoc-logo-mini.png` and `esdoc-logo-mini-black.png`
- `github.png`
- `search.png`


### `src/Publisher/Builder/template/layout.html`

The markup has been largely modified to fit the responsive purpose.

In the `<head>` tag, we have added:
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>`

And at the bottom of the `<body>`, we have added a script:
`<script src="script/menu.js"></script>`


### `src/Publisher/Builder/template/script/inherited-summary.js`

Replace `tbody.style.display = 'block';` with `tbody.style.display = 'table-row-group';`, because it is targeting  a `<table>` tag.


### `src/Publisher/Builder/template/script/manual.js`

Replace `'{ display: block; }\n';` with `'{ display: list-item; }\n';` because  it is targeting a `<li>` tag.


### `src/Publisher/Builder/template/script/menu.js`

A simple script to handle the nav icon and the menu icon on mobile device.


### `src/Publisher/Builder/template/script/search.js`

In the `layout.html`, i have changed the markup of the search:

```html
<div id="esdoc-search">
    <header><input/></header>
    <article><ul></ul></article>
</div>
```

Because of that, the variables are now:
```js
var searchBox = document.querySelector('#esdoc-search');
var input = searchBox.querySelector('header input');
var resultWrapper = searchBox.querySelector('article');
var result = resultWrapper.firstChild;
```
 
And, i have replaced `result.style.display` with `resultWrapper.style.display`.

I have added some code to improve the behavior of the search box.
Now the box is closing when you have finished the search.

**Comment by iursevla** [comment]
This looks good. When will the main project integrate this?

**Comment by h13i32maru** [comment]
@avine Please create a specific plugin for responsive layout. Because, now, ESDoc v1.0 adopts plugin architecture. I would not merge this PR.

**Comment by avine** [comment]
i will do my best to find some time and integrate my work into the new architecture.

**Comment by pixelass** [comment]
I came across this PR when I was looking for esdoc themes.

**So this is for everybody who is looking for the same thing.**

Since I did not really find anything usable or complete and needed something pretty for my projects I went ahead and created a theme that can be loaded via [esdoc-publish-html-plugin](https://yarnpkg.com/en/package/esdoc-publish-html-plugin)

See: [esdoc-custom-theme](https://sinnerschrader.github.io/esdoc-custom-theme/manual/usage.html#basic-usage)

The theme is built with some nifty features like css-grid and css-variables.
This allows easy customisations via [esdoc-inject-style-plugin](https://yarnpkg.com/en/package/esdoc-inject-style-plugin)

I just released a **prerelease version (rc1)**

### Features:

* Responsive
* more classnames
* css from scratch
* system ui fonts with several fallbacks
* works from file system
* codemirror as highlighter
* **Highlighters** javascript, jsx, typescript, scss, css, less, html, xml, json, shell
* reader can switch colorschemes and toggle the dark/light mode for better readablity
* **colorschemes** All from codemirror (reader choosable)
* **modes** dark/light (reader choosable)

modes and colorschemes are saved in localstorage, so if you use the theme in the same github space the settings will persist.

In the end it's all about the people who read the documentation right? Let the reader decide about the appearance.

Screenshots:

screen shot 2018-02-12 at 06 08 06
screen shot 2018-02-12 at 06 08 02
screen shot 2018-02-12 at 06 07 54
screen shot 2018-02-12 at 06 07 29
screen shot 2018-02-12 at 06 07 06
screen shot 2018-02-12 at 06 06 33
screen shot 2018-02-12 at 06 06 17
screen shot 2018-02-12 at 06 06 00
screen shot 2018-02-12 at 06 20 59

**Pull request closed without merging**
