### PR TITLE
fix: crash when [Symbol.iterator] is declared in a class.

### PR DESCRIPTION
**Pull request by noraesae**
Hi,

I've just uploaded the previous PR and I found the issue #73 is somewhat similar to it. However, I cannot be sure if this way is what you would like. Any comment will be welcomed, so that I can modify along with it.

Cheers :+1:

### CODE REVIEW

**Comment by noraesae** [comment]
This may conflict with another PR which has just been merged. I'll update soon :watch:

**Comment by h13i32maru** [comment]
@noraesae Thanks for this PR!
But I want to fix this problem with other approach. Because ``[...](){}`` has any expression.
- ``[foo](){}``
- ``[foo.bar.baz](){}``
- ``[foo + bar](){}``
- ``[foo()](){}``
- etc...

So, I think that generate JS code from the expression AST using [escodegen](https://github.com/estools/escodegen).

**Comment by noraesae** [comment]
Updated PR using the suggested escodegen. Please feel free to comment further!

**Comment by h13i32maru** [comment]
Wow! Thanks updated!

**Pull request merged**
