### PR TITLE
Make layout responsive.

### PR DESCRIPTION
**Pull request by avine**
i have done some work to make the layout responsive.
You can check the result at: ~~http://esdoc.avine.fr/~~ https://avine.io/projects/esdoc/v1/
Just resize the window to see it in action...

### CODE REVIEW

**Comment by avine** [comment]
## screenshot of the responsive menu:
responsive-menu

## and navigation:
responsive-navigation

**Comment by avine** [comment]
Note that on large screen, the layout-container's width is fixed (but it's completely optional):

```css
@media (min-width: 1024px) {
  .layout-container {
    margin: 0 auto;
    width: 1024px; /* Comment this line to disable the feature */
    box-shadow: 0 5px 10px rgba(0, 0, 0, .2);
    box-sizing: border-box;
    border-width: 0 1px;
    border-style: solid;
    border-color: #ddd;
  }
}
```

large-screen

**Comment by avine** [comment]
```.table-wrapper``` class usage:

```html
<div data-ice="properties">
  <h4 data-ice="title">Params:</h4>
  <div class="table-wrapper">
    <table class="params">
    ...
```

table-wrapper

**Comment by avine** [comment]
Here is the new markup for the `.search-box`:
```html
 <div class="search-box">
     <div><input class="search-input"/></div>
     <ul class="search-result"></ul>
 </div>
````

**Comment by avine** [comment]
search-close
search-open
search-result

**Comment by avine** [comment]
By the way, the free icons comes from:
https://www.iconfinder.com/iconsets/developer-set-3

**Comment by avine** [comment]
Here's the new `.search-box` markup:
```html
<div class="search-box">
    <div class="search-input"><input/></div>
    <div class="search-result"><ul></ul></div>
</div>
```

And in `search.js`:
```js
  var resultWrapper = document.querySelector('.search-result');
  var result = resultWrapper.firstChild;
```
Then, simply replace `result.style.display` by `resultWrapper.style.display`.

**Comment by avine** [comment]
Long list of results:
search-result-long

Short list of results:
search-result-short

No result:
search-no-result

**Comment by avine** [comment]
Hi,

First, I really like the amazing job you have done and I will be very happy if you are interested in my contribution.
It would be nice if you could give me a feedback on my work just to know if you like it.
If so, I will be able to go even further in the development.

The roadmap might be to split the CSS into something like:
  - `base.css` (required - contains minimal styles)
  - `theme.css` (optional - contains advanced styles for responsive design and more...)

This way, it will be super easy for anyone to just disable the `theme.css` in order to completely customize the interface in a different way (using the `styles` and `scripts` feature).

The `config`could be:
```javascript
{
  "includeTheme": true, // Include `theme.css` in the `layout.html`
  "styles": ["./path/to/style.css"],
  "scripts": ["./path/to/script.js"]
}
````

Best regards,

**Comment by avine** [comment]
Please check the result at: http://esdoc.avine.fr.

**Comment by florianb** [comment]
👏  i ❤️  it! I hope it gets merged!

**Comment by avine** [comment]
Thanks. I hope too. ;-)Le 13 janv. 2017 3:45 PM, Florian Breisch <notifications@github.com> a écrit :👏  i ❤️  it! I hope it gets merged!

**Comment by h13i32maru** [comment]
thanks a lot!
I will check this, please wait a little.

**Comment by avine** [comment]
Thanks in advance. Feel free to ask me any question. I will be pleased to explain the code if needed.

**Comment by paulondc** [comment]
Great! looking forward to get these changes in esdoc.

**Comment by h13i32maru** [comment]
Please check https://github.com/esdoc/esdoc/pull/379#issuecomment-279212542

**Comment by h13i32maru** [comment]
Please check https://github.com/esdoc/esdoc/pull/379#issuecomment-326794278

**Pull request closed without merging**
