### PR TITLE
Fix Issue 406 esdoc stringify

### PR DESCRIPTION
**Pull request by MattMcFarland**
This is a fix for issue #406 

[JSON.stringify has its limits](https://stackoverflow.com/questions/24153996/is-there-a-limit-on-the-size-of-a-string-in-json-with-node-js), and because of such it can become impossible for large scale / enterprise applications to crash into a screeching halt due to this limitation.

### Streams to the rescue!

By using a stream, we can break apart the large POJO (or Object Literal if you will) into smaller "chunks", stringifying the chunks themselves while not losing any integrity of the data.  In fact, streams can handle gigs of data (this is what they're really good at!)

After @jalexanderfox and I started testing esdoc, we noticed that the testing framework would fail due to race conditions and the assumption that the `esdoc.generate()` method was synchronous.

Because `streams` are Asynchronous by design, we had to refactor the test `init.js` to make sure it runs its tests after the generation was complete.

We also spent a lot of time testing, iterating, and improving the code, and I'm quite proud of the new changes.

Please let me know if anything needs changed.

### CODE REVIEW

**Comment by h13i32maru** [comment]
Thanks!

Please consider the following contents.
- Can you cut out changes into small PRs?
- Do you need to change package.json?
- Since ESDoc does not plan to use yarn, is it possible to delete it?
- Can you implement it as a plugin?

**Comment by MattMcFarland** [comment]
To answer your questions:

```
Can you cut out changes into small PRs?
```
No, this required a lot of changes to fix the bug

```
Do you need to change package.json?
```
Yes, I needed to add `big-json` dependency

```
Since ESDoc does not plan to use yarn, is it possible to delete it?
```
Yes
```
Can you implement it as a plugin?
```
No, this is fixing a bug, not really adding a new feature as this require changing the ESDOC Generator and ESDOC test to switch from JSON.Stringify to Node Stream.  

If I remove yarn, will you accept the PR?

**Comment by h13i32maru** [comment]
> No, this required a lot of changes to fix the bug

OK. So then I need a lot of time to review this. Because this PR is large, I read it slowly.

> and I can reduce the changes though if you would like.

Please do it.

> No, this is fixing a bug, 

I do not think this is a bug. I do not think this is a bug. In fact, it has not been a problem so far.

In the first place, the problem with `JSON.stringify` is to write AST to a file, right? So, if you make it optional, I think that this problem can be avoided. How about that?

**Comment by h13i32maru** [comment]
Because it is difficult to explain in English, I write in Japanese.

`JSON.stringify` をつかってASTを文字列にして、ファイルに書き出すところに問題があるという理解です。現実的にはこれまで問題になってきていませんでした。なので、このような大きな変更を入れるのは反対です。私の理解がただしければ、ASTをファイルに書き出すというのをオプションにすることで、この問題を回避できると思います。

**Comment by MattMcFarland** [comment]
Actually I can make this have a lot less changes, I am working on it now!

**Pull request closed without merging**
