### PR TITLE
Create new alias tags for @property/@prop and @description/@desc

### PR DESCRIPTION
**Pull request by blindman**
applies to #153

### CODE REVIEW

**Comment by mmoss** [comment]
+1

**Comment by h13i32maru** [comment]
Sorry, I have the policy that each tags do not have alias. Because multi ways confuse users.

**Comment by blindman** [comment]
@h13i32maru That seems like an odd assetion, do you have scenarios to back that up?

Don't get me wrong, I'm not trying to force you to merge this in I just feel like that's a bit of a wild statement.

**Comment by gbabula** [comment]
@h13i32maru @blindman @mmoss 

Just to bump this topic, whats the logic behind supporting `@desc` and not `@description`? In my opinion `@description`, although more verbose - makes a lot more sense and is easier to scan when reading documentation within a codebase. This also creates more diversion between JSDoc and ESDoc, since JSDocs supports both aliases...

**Comment by gbabula** [comment]
I'll also note that `@return` is officially documented, however both `@return` and `@returns` appear to work, so there is already some divergence from your initial statement.

**Pull request closed without merging**
